name: Build + Tests

on:
  workflow_call:

jobs:
  build:
    name: Build + Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Build + Test
        run: make test
