name: Orchestrator

on:
  push:
    branches: [master]
  pull_request:
    branches: ['rc-*', master]

jobs:
  build:
    uses: ./.github/workflows/ci/build.yml

  examples:
    uses: ./.github/workflows/ci/examples.yml
